openapi: 3.0.0
info:
  title: Social App
  description: An API which returns username, followers and follows of Facebook, Instagram and Linked to User.
  version: 1.0.1

servers:
  - url: http://localhost:5000/api/v1
    description: Localhost Version of App
  - url: https://socialapi-lco.herokuapp.com/
    description: Heroku Hosted API URL

components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
    BearerAuth:
      type: http
      scheme: bearer

paths:
  /instagram:
    get:
      summary: It returns Username, Followers and Follows.
      responses:
        "200": # Status Code
          description: Returns an Object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: number
                  follows:
                    type: number
    post:
      summary: It returns Username, Followers and Follows.
      responses:
        "200": # Status Code
          description: Returns an Object
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  followers:
                    type: number
                  follows:
                    type: number

  /{random}:
    get:
      summary: It returns whatever is there in parameter.
      parameters:
        - name: random
          default: 5
          in: path
          schema:
            type: string
      responses:
        "200": # Status Code
          description: Returns a string.
          content:
            application/json:
              schema:
                type: object
                properties:
                  params:
                    type: string
